### ISSUE TITLE
Работает ли приложение?

### ISSUE THREAD

**Issue by LennyLip** [DrMartiner/django-yandex-money#2]
https://money.yandex.ru/doc.xml?id=526025

пишут устарела документация.

А приложение то рабочее или уже нет?

**Comment by LennyLip** [comment]
Да , и и еще в догонку вопрос.

Это приложение для Яндекс.Касса или для формы приема платеже?

Или там одинаковый API? (я пока не разбирался с вопросом)

**Comment by degibenz** [comment]
@LennyLip Касса работает посредством API Яндекс.Деньги.

**Comment by LennyLip** [comment]
@degibenz походу вот приложение более правильное
https://github.com/yandex-money/yandex-money-kit-django

**Comment by DrMartiner** [comment]
@LennyLip @degibenz сорри, уведомления были выключены. https://github.com/DrMartiner/django-yandex-kassa - вот новое приложение для Яндекс денег (скоро появятся массовые выплаты) 

https://github.com/yandex-money/yandex-money-kit-django - это мое приложение; только там ссылки на меня нет - какой-то олень из Я скопировал и залил из под себя
